# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='cv.CV'),
        ),
    ]
