# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme'),
        ),
    ]
